# Paths on JUQUEEN using tmLQCD
USER_MAIL="sciarra@th.physik.uni-frankfurt.de"
HMC_BUILD_PATH="tmLQCD/Program/build"
SIMULATION_PATH="WilsonProject"
HOME_DIR="/homeb/hkf8/hkf805" 
WORK_DIR="/work/hkf8/hkf805" 
SCRIPT_DIR="$HOME_DIR/Script/tmLQCD_Juqueen"
HMC_FILENAME="hmc_tm"
HMC_GLOBALPATH="$HOME_DIR/$HMC_BUILD_PATH/$HMC_FILENAME"
INPUTFILE_NAME="hmc.input"
JOBSCRIPT_PREFIX="job.script"
OUTPUTFILE_NAME="output.data"
