# Paths on LOEWE using CL2QCD
USER_MAIL="czaban@th.physik.uni-frankfurt.de"
HMC_BUILD_PATH="tmLQCD_imagMu_Juqueen/Program/build"
SIMULATION_PATH="ImagMu_Output_Data"
HOME_DIR="/homeb/hkf8/hkf806" 
WORK_DIR="/work/hkf8/hkf806" 
SCRIPT_DIR="$HOME_DIR/Script/tmLQCD_Juqueen"
PRODUCEJOBSCRIPTSH="$HOME_DIR/Script/JobScriptAutomation/ProduceJobScript.sh"
PRODUCEINPUTFILESH="$HOME_DIR/Script/JobScriptAutomation/ProduceInputFile.sh"
HMC_TM_FILENAME="hmc_tm"
HMC_TM_GLOBALPATH="$HOME_DIR/$HMC_BUILD_PATH/$HMC_TM_FILENAME"
INPUTFILE_NAME="hmc.input"
JOBSCRIPT_PREFIX="job.hmc.cl2qcd.loewe"
OUTPUTFILE_NAME="hmc.output"
